from turtle import *
# colors can be hex codes or color names

getscreen().bgcolor("black")
#This function will change the color of the background

color("red")
circle(int(100))
circle(int(50))
circle(int(25))
color("white")
forward(distance=int(120))
color("orange")
circle(int(25))
circle(int(50))
circle(int(100))
right(angle=int(90))
color("yellow")
circle(int(25))
circle(int(50))
circle(int(100))
right(angle=int(90))
color("green")
circle(int(25))
circle(int(50))
circle(int(100))
color('white')
forward(distance=int(120))
right(angle=int(90))
color("blue")
circle(int(25))
circle(int(50))
circle(int(100))
left(angle=int(90))
color("purple")
circle(int(25))
circle(int(50))
circle(int(100))
right(angle=int(180))

done()
