from turtle import *

getscreen().bgcolor("black")
color("red")
circle(int(100))
circle(int(50))
circle(int(25))
color("lightblue")
forward(distance=int(120))
color("orange")
circle(int(25))
circle(int(50))
circle(int(100))
right(angle=int(90))
color("yellow")
circle(int(25))
circle(int(50))
circle(int(100))
right(angle=int(90))
color("green")
circle(int(25))
circle(int(50))
circle(int(100))
color("lightblue")
forward(distance=int(120))
right(angle=int(90))
color("blue")
circle(int(25))
circle(int(50))
circle(int(100))
left(angle=int(90))
color("purple")
circle(int(25))
circle(int(50))
circle(int(100))
color("lightblue")
right(angle=int(120))
forward(distance=int(120))
right(angle=int(120))
forward(distance=int(120))



# if you are using a local environment such as
# Visual Studio Code, add "done()" at the end
# to prevent the output window from closing 
done()